config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :restaurants, only: %i[index new create show] do
    resources :reviews, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  validates :name, :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"],
    message: 'is note a valid category'}
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5), message: 'is not a valid rating'}, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  def index
    @restaurants = Restaurant.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
      if @restaurant.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new, status: :unprocessable_entity
      end
  end

 private

 def restaurant_params
  params.require(:restaurant).permit(:name, :category, :address, :phone_number)
 end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
      if @review.save
        redirect_to restaurant_path(@restaurant)
      else
        render :new, status: :unprocessable_entity
      end
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Page Restaurants</h1>

<div class="container">
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to restaurant.name, restaurant_path(restaurant) %>
    </li>
  <% end %>
</ul>
<%= link_to 'Add a restaurant', new_restaurant_path %>

</div>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="w-50">
    <%= simple_form_for @restaurant do |f| %>
      <%= f.input :name, placeholder: 'Restaurant\'s Name'%>
      <%= f.input :address, placeholder: 'City' %>
      <%= f.input :phone_number, placeholder: 'Phone Number' %>
      <%= f.input :category, collection: %w(chinese italian japanese french belgian) %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<h1>Page Show</h1>

<h2><%= @restaurant.name %></h2>

<p><%= @restaurant.address%></p>
<p><%= @restaurant.category%></p>
<p><%= @restaurant.phone_number%></p>

<h3>Avis:</h3>
<ul>
  <% @restaurant.reviews.each do |review| %>
  <li><%= review.content %>: <%= review.rating %></li>
  <% end %>
</ul>

<%= link_to 'Ajouter un avis ➕', new_restaurant_review_path(@restaurant) %>

app/views/reviews/new.html.erb
<div class="container">
  <div class="w-50">
    <%= simple_form_for [@restaurant, @review] do |f| %>
      <%= f.input :content, placeholder: 'Your review'%>
      <%= f.input :rating, collection: %w(0 1 2 3 4 5) %>
      <%= f.button :submit, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>